# deployment/cloud-build.yaml
steps:
  # Build and push backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agentic-ai-backend', './backend']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agentic-ai-backend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agentic-ai-backend'
      - '--image=gcr.io/$PROJECT_ID/agentic-ai-backend'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--concurrency=80'
      - '--timeout=3600'
      - '--set-env-vars=DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY},VERTEX_AI_PROJECT_ID=$PROJECT_ID'
  
  # Get backend URL
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting backend URL for frontend build..."
        export BACKEND_URL=$(gcloud run services describe agentic-ai-backend --platform managed --region ${_REGION} --format 'value(status.url)')
        echo "BACKEND_URL=$BACKEND_URL" >> /workspace/frontend/.env
  
  # Build frontend with backend URL
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/agentic-ai-frontend', 
      '--build-arg', 
      'REACT_APP_API_URL=$(cat /workspace/frontend/.env | grep BACKEND_URL | cut -d "=" -f2)',
      './frontend'
    ]
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agentic-ai-frontend']
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agentic-ai-frontend'
      - '--image=gcr.io/$PROJECT_ID/agentic-ai-frontend'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _DATABASE_URL: 'postgresql://postgres:password@localhost:5432/agentic_ai'
  _SECRET_KEY: 'change-this-to-a-secure-secret-key'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/agentic-ai-backend'
  - 'gcr.io/$PROJECT_ID/agentic-ai-frontend'
